### ISSUE TITLE
fix Ruta de stripe

### ISSUE THREAD

**Issue by JuanCarlosRL** [HouseRent16/PGPI-G2.11#111]
La ruta de stripe en caso de cancelar no te lleva a ningún lado

**Comment by alepervaz** [comment]
Esta arreglado ya cuando niegas el pago la reserva se borra y te manda al catalogo e igual si aceptas la compra que se activa el pagado y te manda al catalogo

**Comment by alepervaz** [comment]
FINALIZADO A FALTA DE REVISION DEL GRUPO
