### ISSUE TITLE
fix Número de teléfonos en el perfíl

### ISSUE THREAD

**Issue by JuanCarlosRL** [HouseRent16/PGPI-G2.11#112]
En el perfíl el número de teléfono si no es español no se hace bien el formateo

![image](https://github.com/HouseRent16/PGPI-G2.11/assets/72872031/99e760e3-2cf0-4ef0-a54b-e290cf00c4d0)

**Comment by marvicmar** [comment]
Ya funciona, era problema de como esta definido en el populate.json, al ser otro prefijo tiene un formato distinto al español.
