### ISSUE TITLE
Fix: Muchos atributos en la imagen

### ISSUE THREAD

**Issue by CarmenRuizPorcel** [HouseRent16/PGPI-G2.11#131]
La imagen tiene un atributo de titulo, descripcion y otro de texto alternativo, no los estamos usando en ningun momento por lo que los podriamos quitar perfectamente
Cambiar la entidad y el formulario de añadir imagen

**Comment by marvicmar** [comment]
Ya he eliminado la descipción de image, el campo alt no lo quitaría ya que está en muchos archivos htlm, y es más trabajo que no merece la pena. En todo caso podría ver si el titulo es menos usado.

**Comment by marvicmar** [comment]
## Description 
Por otro lado he encontrado un fallo, y es que el formulario de imagenes petaba al introducir dos imagenes con el mismo order, de momento solo lo he metido en un try, except para que no salte la pantalla de error fea, pero habría que gestionarlo. Yo votaría por quitar el campo order porque de todos modos, no le vamos a dar opción una vez creada las imagenes a alterar su orden, y es complicar la lógica. He dejado un comentario puesto en el código como ToDo.

## image 
![imagen](https://github.com/HouseRent16/PGPI-G2.11/assets/73558808/43f0da0b-2093-4f0f-bb8b-9c1c819efd2a)

**Comment by marvicmar** [comment]
No se podía eliminar order ya que se usaba en muchas funciones para filtar y mostrar la imagen, y como ya no teníamos problemas de capacidad. Lo que he hecho es eliminarla del formulario de imagen, y hacer que sea un campo que se auto incremente.
