### ISSUE TITLE
Fix: Pestaña reservas owner

### ISSUE THREAD

**Issue by CarmenRuizPorcel** [HouseRent16/PGPI-G2.11#132]
Borrar pestaña reservas en el owner (o cambiar como funciona)
Ahora mismo el owner puede ver la reservas hechas por los usuario en la pestaña de gestión (pulsando el alojamiento), creo que no funciona del todo bien. Adjunto foto:
![image](https://github.com/HouseRent16/PGPI-G2.11/assets/72879200/2d93033e-fc4c-46d9-a40c-3f24a4e4f15b)
![image](https://github.com/HouseRent16/PGPI-G2.11/assets/72879200/987e9ae9-e5d9-4121-b4c7-b0c87f60a0ee)
![image](https://github.com/HouseRent16/PGPI-G2.11/assets/72879200/5a84b37a-f7c6-4f30-b1cf-2c8e214dcb13)

Propongo dos opciones:
 - Modificar la pestaña de reservas en owner, la pestaña estaria igual estruturadas pero en vez de las reservas hechas por el owner salgan las hechas por todos los users con boton cancelar reserva
 - Arreglar el apartado de reservas de los detalles de owner con boton cancelar reserva

**Comment by alepervaz** [comment]
He hecho que el botón de reservas solo te salga cuando eres user si eres owner no sale
![Captura desde 2023-12-08 18-13-35](https://github.com/HouseRent16/PGPI-G2.11/assets/73081268/b78c1466-3e27-4d3d-93d4-c7689baf40a0)
Luego en el apartado de gestion he añadido la funcionalidad correcta para que como owner puedas cancelar la reserva de los usuarios 
![Captura desde 2023-12-08 18-14-08](https://github.com/HouseRent16/PGPI-G2.11/assets/73081268/dbf74b3f-b8e4-422a-81de-72113d0f9f78)

**Comment by CarmenRuizPorcel** [comment]
puedes cambiar que en la parte superior de la tabla no salga servicio?  no entiendo muy bien esa etiqueta, no sirve para nada. En lugar del servicio pondría el correo de quien ha hecho la reserva
