### ISSUE TITLE
Fix: Botón de reclamar en reservas canceladas

### ISSUE THREAD

**Issue by CarmenRuizPorcel** [HouseRent16/PGPI-G2.11#134]
El usuario deberia poder reclamar si cancela la reserva o le cancelan la reserva

**Comment by alepervaz** [comment]
ya he añadido un botón para cancelar una reserva
![Captura desde 2023-12-08 18-44-32](https://github.com/HouseRent16/PGPI-G2.11/assets/73081268/3e9e36a7-9645-4f7a-9c41-a33da230bf69)
Sin embargo tengo la duda de como veis arriba si eres user no te sale el apartado de reclamaciones , asimismo he visto que carmen esta haciendo una tarea la cual e gestionar reclamaciones #136 no se si es que lo corrige, no he querido tocarlo por no meterme en lo suyo. Si al final no esta lo añado yo un momento
