### ISSUE TITLE
Fix: Quitar hora en la fecha de inicio y fin en el detalles de la reserva

### ISSUE THREAD

**Issue by CarmenRuizPorcel** [HouseRent16/PGPI-G2.11#135]
Poner que la reserva empieza a las 00:00 de x dia y termina a las 00:00 de y dia no tienen ningun sentido, cono no podemos guardar exactamente la hora de la reserva será mejor no mostrarla porque no sirve para nada, y confunde más que ayuda.
![image](https://github.com/HouseRent16/PGPI-G2.11/assets/72879200/48ad990d-e1b2-41fb-9d3b-d7ed448ad03e)

**Comment by sergiosant02** [comment]
Mejor no hacerlo así Maria, porque tenemos un apartado para escribir la info de llegada aunque es en formato texto
