### ISSUE TITLE
Feat: Gestionar reclamaciones 

### ISSUE THREAD

**Issue by CarmenRuizPorcel** [HouseRent16/PGPI-G2.11#136]
Propongo dos soluciones, una sencilla (y que no es genial) y otra un poco más larga (una solución más acertada):
- Poner un boton al lado de cada reclamación que sea resolver reclamación, eliminar esa reclamación cuenta como resuelta. Deberíamos poner en a tabla el mail de quien hace la reclamación para justificar que la reclamación se gestiona en otro departamento.
Esto además nos permitiria liberar memoria una ve "resuelta" la reclamación.
- Poner un boton o para enviar un mail automatico (se deberia poder poner un form que añadirá ese texto al mail) o para contestar a la reclamación (deberiamos hacer una vista para ver la reclamación y la respuesta para user)

**Comment by sergiosant02** [comment]
Se ha cambiado el estilo de la página de respuestas de reclamaciones
<img width="1347" alt="Captura de pantalla 2023-12-10 a las 16 22 54" src="https://github.com/HouseRent16/PGPI-G2.11/assets/54277294/68432d7b-3355-4b18-836e-921e8151bf9e">
y se han solucionado los problemas con el email
