### ISSUE TITLE
Fix: No se añade los nuevos alojamientos

### ISSUE THREAD

**Issue by CarmenRuizPorcel** [HouseRent16/PGPI-G2.11#137]
No se añaden al catalogo los alojamientos creados, solo se añade a gestión pero lo users no lo pueden ver
Gestion:
![image](https://github.com/HouseRent16/PGPI-G2.11/assets/72879200/b0d91d65-5b6b-4b91-a517-6feaec7cc061)
Catálogo:
![image](https://github.com/HouseRent16/PGPI-G2.11/assets/72879200/48aece3c-191e-4ff5-a322-b038df53e491)

**Comment by marvicmar** [comment]
Ya debería de estar arreglado, era por el campo is_active que se estaba añandiendo con ese campo a False.
