### ISSUE TITLE
Fix: Cambiar correos usuarios en el Populate

### ISSUE THREAD

**Issue by marvicmar** [HouseRent16/PGPI-G2.11#143]
## Description
Deberíamos poner correos reales, para poder mostrar el correcto funcionamento de los envios de los mismo en la aplicación

**Comment by alepervaz** [comment]
He añadido la cuenta de correo de la universidad de todos es decir <uvus>@alum.us.es y he comprobado que con cada uno de ellos se puede realizar una reserva con que os tiene que haber llegado un correo, para que podais hacer pruebas. 
![Captura desde 2023-12-08 13-36-51](https://github.com/HouseRent16/PGPI-G2.11/assets/73081268/544d9623-9f75-491a-a48d-276430745505)
Sin embargo tengo tambien una duda en el sentido de si es necesario que borre el admin que iria en relacion con la issue #130. En funcion de lo que hagamos con eso actualizo de nuevo el populate dejandolo de la forma correcta

**Comment by alepervaz** [comment]
he añadido tambien la cuenta de propietario, esta sera la cuenta qye sergio creo para enviar los correos houserent2324@gmail.com y la contraseña es houserent2324
![Captura desde 2023-12-08 17-15-09](https://github.com/HouseRent16/PGPI-G2.11/assets/73081268/28f2668b-30b5-4fbb-9aa7-8c7c7a98bc1e)
