### ISSUE TITLE
fix Estado de detalles de reserva

### ISSUE THREAD

**Issue by JuanCarlosRL** [HouseRent16/PGPI-G2.11#95]
El estado de detalles de reserva no se muestra adecuadamente.

![image](https://github.com/HouseRent16/PGPI-G2.11/assets/72872031/e1cded1d-60cb-4050-af05-cc31a24b764c)

**Comment by sergiosant02** [comment]
Ya se ha cambiado el aspecto de los detalles
![Captura de pantalla 2023-12-10 a las 16 28 14](https://github.com/HouseRent16/PGPI-G2.11/assets/54277294/eb57a75e-5ff1-4a4b-b03b-6f0a9db9638e)
